#!/bin/sh

commit_template_f="./.gitmessage"
old_msg_f="./xx00"
default_f="./xx01"

BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')

if [ $BRANCH_NAME == '(no branch)' ]; then
    exit 1
fi

if grep "^\(feat\|fix\|conf\|ci\|docs\|wip\):" $1; then
    commit_msg_no_head=$(tail -n +2 $commit_template_f)

    csplit $1 /#/
    old_msg=$(cat $old_msg_f)
    default=$(cat $default_f)
    rm $old_msg_f
    rm "$default_f"

    printf "$old_msg\n$commit_msg_no_head$default" > $1
else
    commit_msg_template=$(cat $commit_template_f)
    printf "$commit_msg_template\n$(cat $1)" > $1
fi

